const fs = require('fs');
const path = require('path');

async function extractResume() {
  try {
    // Dynamic import for ES module
    const pdfjsLib = await import('pdfjs-dist/legacy/build/pdf.mjs');
    
    // Path to the resume PDF (in the app/public folder)
    const pdfPath = path.join(__dirname, '../../app/public/resume.pdf');
    
    if (!fs.existsSync(pdfPath)) {
      console.error('Error: resume.pdf not found at', pdfPath);
      console.log('Make sure the resume.pdf exists in app/public/');
      process.exit(1);
    }

    console.log('Reading PDF from:', pdfPath);
    
    const dataBuffer = fs.readFileSync(pdfPath);
    const uint8Array = new Uint8Array(dataBuffer);
    
    const loadingTask = pdfjsLib.getDocument({ data: uint8Array });
    const pdfDocument = await loadingTask.promise;
    
    console.log(`PDF loaded. Pages: ${pdfDocument.numPages}`);
    
    // Extract text from all pages
    const textContent = [];
    
    for (let i = 1; i <= pdfDocument.numPages; i++) {
      const page = await pdfDocument.getPage(i);
      const content = await page.getTextContent();
      const pageText = content.items
        .map((item) => item.str || '')
        .join(' ');
      textContent.push(pageText);
      console.log(`Extracted page ${i}`);
    }
    
    const resumeText = textContent.join('\n\n');
    
    // Generate the TypeScript file
    const outputContent = `// This file is auto-generated by \`npm run update-resume\`
// Do not edit manually - update the resume.pdf and run the script

export const RESUME_TEXT = \`${resumeText.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;

export const SYSTEM_PROMPT = \`You are Emil Ismayilzada's personal AI assistant on his portfolio website. Your role is to help recruiters, hiring managers, and visitors learn about Emil's professional background, skills, projects, and experience.

Here is Emil's complete resume and background information:

\${RESUME_TEXT}

## Your Guidelines:

1. **Be Helpful and Professional**: Answer questions about Emil's experience, skills, education, and projects in a friendly and professional manner.

2. **Stay Factual**: Only provide information that is in the resume context. If asked about something not covered, politely explain that you don't have that information and suggest they reach out to Emil directly.

3. **Highlight Relevant Experience**: When answering questions, emphasize Emil's most relevant experience and achievements. For example:
   - Current role at BMW Group as Data Analyst
   - Experience with modern technologies (Python, React, LLMs, etc.)
   - Strong educational background with high GPAs
   - Diverse project portfolio

4. **Be Concise but Thorough**: Provide comprehensive answers but avoid being overly verbose. Use bullet points when listing multiple items.

5. **Encourage Contact**: When appropriate, encourage visitors to connect with Emil via LinkedIn or email for more detailed discussions.

6. **Handle Off-Topic Gracefully**: If asked about topics unrelated to Emil, politely redirect the conversation back to his professional profile.

7. **Show Personality**: Be warm and engaging while maintaining professionalism. You represent Emil, so be respectful and positive.

Remember: You are Emil's wingman for recruiters. Your goal is to present Emil in the best light while being honest and accurate about his qualifications.\`;
`;

    const outputPath = path.join(__dirname, '../src/resume-context.ts');
    fs.writeFileSync(outputPath, outputContent);
    
    console.log('\n✓ Resume context updated successfully!');
    console.log('Output:', outputPath);
    console.log('\nNext steps:');
    console.log('1. Review the generated file');
    console.log('2. Run `npm run deploy` to deploy the worker');
    
  } catch (error) {
    console.error('Error extracting resume:', error);
    process.exit(1);
  }
}

extractResume();
